### PR TITLE
enabled security features DEP and ASLR

### PR DESCRIPTION
**Pull request by chcg**
- updated n++ interface files from https://github.com/npp-plugins/plugintemplate v3.1
- avoid post build copy action, if n++ dir doesn't exist
- enabled security features DEP (https://msdn.microsoft.com/de-de/library/aa366553(vs.85).aspx) and ASLR (https://en.wikipedia.org/wiki/Address_space_layout_randomization#Microsoft_Windows) in VS config

CI build see https://ci.appveyor.com/project/chcg/doxyit/build/0.3.0.5
appveyor.yml config could be easily adapted regarding usage of v140_xp, publish artifacts, enable github deployment, for usage github project just needs to be registered at appveyor

### CODE REVIEW

**Comment by dail8859** [comment]
Just curious, what's with the appveyor "crusade"?

**Comment by chcg** [comment]
Sorry, the appveyor is just a sideeffect. Just as assurance for me not to break anything.

The main thing is the activation of DEP and ASLR for enhanced security.

**Comment by dail8859** [comment]
Thanks for the PR. These changes seem fine. If you remove the appveyor.yml file then I'll merge it.

**Comment by chcg** [comment]
Done.

**Comment by dail8859** [comment]
Thanks!

**Pull request merged**
